/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SessionsCounter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CounterTest {
    @Test void appHasAGreeting() {
       Counter classUnderTest;
        classUnderTest = new Counter();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
